# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Geom.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QuadControl(object):
    def setupUi(self, QuadControl):
        QuadControl.setObjectName(_fromUtf8("QuadControl"))
        QuadControl.resize(241, 411)
        self.groupBox_2 = QtGui.QGroupBox(QuadControl)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 221, 381))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Up = QtGui.QPushButton(self.groupBox_2)
        self.Up.setGeometry(QtCore.QRect(80, 280, 61, 51))
        self.Up.setObjectName(_fromUtf8("Up"))
        self.IncrementLabel = QtGui.QLabel(self.groupBox_2)
        self.IncrementLabel.setGeometry(QtCore.QRect(30, 238, 91, 21))
        self.IncrementLabel.setObjectName(_fromUtf8("IncrementLabel"))
        self.Quadrant0 = QtGui.QCheckBox(self.groupBox_2)
        self.Quadrant0.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.Quadrant0.setObjectName(_fromUtf8("Quadrant3"))
        self.Quadrant1 = QtGui.QCheckBox(self.groupBox_2)
        self.Quadrant1.setGeometry(QtCore.QRect(120, 10, 91, 20))
        self.Quadrant1.setObjectName(_fromUtf8("Quadrant0"))
        self.Quadrant2 = QtGui.QCheckBox(self.groupBox_2)
        self.Quadrant2.setGeometry(QtCore.QRect(10, 125, 91, 20))
        self.Quadrant2.setObjectName(_fromUtf8("Quadrant1"))
        self.Quadrant3 = QtGui.QCheckBox(self.groupBox_2)
        self.Quadrant3.setGeometry(QtCore.QRect(120, 125, 91, 20))
        self.Quadrant3.setObjectName(_fromUtf8("Quadrant2"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(140, 238, 51, 21))
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.Down = QtGui.QPushButton(self.groupBox_2)
        self.Down.setGeometry(QtCore.QRect(80, 330, 61, 51))
        self.Down.setObjectName(_fromUtf8("Down"))
        self.Right = QtGui.QPushButton(self.groupBox_2)
        self.Right.setGeometry(QtCore.QRect(140, 330, 61, 51))
        self.Right.setObjectName(_fromUtf8("Right"))
        self.Left = QtGui.QPushButton(self.groupBox_2)
        self.Left.setGeometry(QtCore.QRect(20, 330, 61, 51))
        self.Left.setObjectName(_fromUtf8("Left"))
        self.Q0X = QtGui.QLineEdit(self.groupBox_2)
        self.Q0X.setGeometry(QtCore.QRect(50, 45, 51, 21))
        self.Q0X.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Q0X.setObjectName(_fromUtf8("Q0X"))
        self.Q0Y = QtGui.QLineEdit(self.groupBox_2)
        self.Q0Y.setGeometry(QtCore.QRect(50, 80, 51, 21))
        self.Q0Y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Q0Y.setObjectName(_fromUtf8("Q0Y"))
        self.IncrementLabel_2 = QtGui.QLabel(self.groupBox_2)
        self.IncrementLabel_2.setGeometry(QtCore.QRect(10, 45, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.IncrementLabel_2.setFont(font)
        self.IncrementLabel_2.setObjectName(_fromUtf8("IncrementLabel_2"))
        self.IncrementLabel_3 = QtGui.QLabel(self.groupBox_2)
        self.IncrementLabel_3.setGeometry(QtCore.QRect(10, 80, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.IncrementLabel_3.setFont(font)
        self.IncrementLabel_3.setObjectName(_fromUtf8("IncrementLabel_3"))
        self.Q1Y = QtGui.QLineEdit(self.groupBox_2)
        self.Q1Y.setGeometry(QtCore.QRect(160, 80, 51, 21))
        self.Q1Y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Q1Y.setObjectName(_fromUtf8("Q1Y"))
        self.IncrementLabel_4 = QtGui.QLabel(self.groupBox_2)
        self.IncrementLabel_4.setGeometry(QtCore.QRect(120, 45, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.IncrementLabel_4.setFont(font)
        self.IncrementLabel_4.setObjectName(_fromUtf8("IncrementLabel_4"))
        self.Q1X = QtGui.QLineEdit(self.groupBox_2)
        self.Q1X.setGeometry(QtCore.QRect(160, 45, 51, 21))
        self.Q1X.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Q1X.setObjectName(_fromUtf8("Q1X"))
        self.IncrementLabel_5 = QtGui.QLabel(self.groupBox_2)
        self.IncrementLabel_5.setGeometry(QtCore.QRect(120, 80, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.IncrementLabel_5.setFont(font)
        self.IncrementLabel_5.setObjectName(_fromUtf8("IncrementLabel_5"))
        self.Q2Y = QtGui.QLineEdit(self.groupBox_2)
        self.Q2Y.setGeometry(QtCore.QRect(50, 190, 51, 21))
        self.Q2Y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Q2Y.setObjectName(_fromUtf8("Q2Y"))
        self.Q3X = QtGui.QLineEdit(self.groupBox_2)
        self.Q3X.setGeometry(QtCore.QRect(160, 160, 51, 21))
        self.Q3X.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Q3X.setObjectName(_fromUtf8("Q3X"))
        self.IncrementLabel_6 = QtGui.QLabel(self.groupBox_2)
        self.IncrementLabel_6.setGeometry(QtCore.QRect(120, 190, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.IncrementLabel_6.setFont(font)
        self.IncrementLabel_6.setObjectName(_fromUtf8("IncrementLabel_6"))
        self.Q3Y = QtGui.QLineEdit(self.groupBox_2)
        self.Q3Y.setGeometry(QtCore.QRect(160, 190, 51, 21))
        self.Q3Y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Q3Y.setObjectName(_fromUtf8("Q3Y"))
        self.IncrementLabel_7 = QtGui.QLabel(self.groupBox_2)
        self.IncrementLabel_7.setGeometry(QtCore.QRect(10, 160, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.IncrementLabel_7.setFont(font)
        self.IncrementLabel_7.setObjectName(_fromUtf8("IncrementLabel_7"))
        self.Q2X = QtGui.QLineEdit(self.groupBox_2)
        self.Q2X.setGeometry(QtCore.QRect(50, 160, 51, 21))
        self.Q2X.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Q2X.setObjectName(_fromUtf8("Q2X"))
        self.IncrementLabel_8 = QtGui.QLabel(self.groupBox_2)
        self.IncrementLabel_8.setGeometry(QtCore.QRect(10, 190, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.IncrementLabel_8.setFont(font)
        self.IncrementLabel_8.setObjectName(_fromUtf8("IncrementLabel_8"))
        self.IncrementLabel_9 = QtGui.QLabel(self.groupBox_2)
        self.IncrementLabel_9.setGeometry(QtCore.QRect(120, 160, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.IncrementLabel_9.setFont(font)
        self.IncrementLabel_9.setObjectName(_fromUtf8("IncrementLabel_9"))
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(10, 105, 201, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(10, 215, 201, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.groupBox_2)
        self.line_3.setGeometry(QtCore.QRect(10, 265, 201, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(self.groupBox_2)
        self.line_4.setGeometry(QtCore.QRect(110, 15, 3, 80))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.groupBox_2)
        self.line_5.setGeometry(QtCore.QRect(110, 130, 3, 80))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))

        self.retranslateUi(QuadControl)
        QtCore.QMetaObject.connectSlotsByName(QuadControl)

    def retranslateUi(self, QuadControl):
        QuadControl.setWindowTitle(_translate("QuadControl", "Form", None))
        self.Up.setText(_translate("QuadControl", "Up", None))
        self.IncrementLabel.setText(_translate("QuadControl", "Increment (px)", None))
        self.Quadrant0.setText(_translate("QuadControl", "Quadrant:3", None))
        self.Quadrant1.setText(_translate("QuadControl", "Quadrant:0", None))
        self.Quadrant2.setText(_translate("QuadControl", "Quadrant:2", None))
        self.Quadrant3.setText(_translate("QuadControl", "Quadrant:1", None))
        self.lineEdit.setText(_translate("QuadControl", "1", None))
        self.Down.setText(_translate("QuadControl", "Down", None))
        self.Right.setText(_translate("QuadControl", "Right", None))
        self.Left.setText(_translate("QuadControl", "Left", None))
        self.Q0X.setText(_translate("QuadControl", "0", None))
        self.Q0Y.setText(_translate("QuadControl", "0", None))
        self.IncrementLabel_2.setText(_translate("QuadControl", "Shift X", None))
        self.IncrementLabel_3.setText(_translate("QuadControl", "Shift Y", None))
        self.Q1Y.setText(_translate("QuadControl", "0", None))
        self.IncrementLabel_4.setText(_translate("QuadControl", "Shift X", None))
        self.Q1X.setText(_translate("QuadControl", "0", None))
        self.IncrementLabel_5.setText(_translate("QuadControl", "Shift Y", None))
        self.Q2Y.setText(_translate("QuadControl", "0", None))
        self.Q3X.setText(_translate("QuadControl", "0", None))
        self.IncrementLabel_6.setText(_translate("QuadControl", "Shift Y", None))
        self.Q3Y.setText(_translate("QuadControl", "0", None))
        self.IncrementLabel_7.setText(_translate("QuadControl", "Shift X", None))
        self.Q2X.setText(_translate("QuadControl", "0", None))
        self.IncrementLabel_8.setText(_translate("QuadControl", "Shift Y", None))
        self.IncrementLabel_9.setText(_translate("QuadControl", "Shift X", None))

