# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HitFinding.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

try:
    from PyQt5 import QtCore, QtGui
except:
    from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(324, 868)
        Form.setMinimumSize(QtCore.QSize(324, 868))
        Form.setMaximumSize(QtCore.QSize(324, 868))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(12, 590, 300, 220))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 220))
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 200))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 31, 243, 179))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        #self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(150, 0))
        self.label_3.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.Threshold = QtGui.QLineEdit(self.layoutWidget)
        self.Threshold.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Threshold.setFont(font)
        self.Threshold.setObjectName(_fromUtf8("Threshold"))
        self.gridLayout_4.addWidget(self.Threshold, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.Npixels = QtGui.QLineEdit(self.layoutWidget)
        self.Npixels.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Npixels.setFont(font)
        self.Npixels.setObjectName(_fromUtf8("Npixels"))
        self.gridLayout_4.addWidget(self.Npixels, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.FindBragg = QtGui.QComboBox(self.layoutWidget)
        self.FindBragg.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.FindBragg.setFont(font)
        self.FindBragg.setEditable(False)
        self.FindBragg.setObjectName(_fromUtf8("FindBragg"))
        self.FindBragg.addItem(_fromUtf8(""))
        self.FindBragg.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.FindBragg, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.BraggThreshold = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BraggThreshold.sizePolicy().hasHeightForWidth())
        self.BraggThreshold.setSizePolicy(sizePolicy)
        self.BraggThreshold.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.BraggThreshold.setFont(font)
        self.BraggThreshold.setObjectName(_fromUtf8("BraggThreshold"))
        self.gridLayout_4.addWidget(self.BraggThreshold, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 4, 0, 1, 1)
        self.cpus = QtGui.QLineEdit(self.layoutWidget)
        self.cpus.setMinimumSize(QtCore.QSize(25, 0))
        self.cpus.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cpus.setFont(font)
        self.cpus.setObjectName(_fromUtf8("cpus"))
        self.gridLayout_4.addWidget(self.cpus, 4, 1, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.layoutWidget)
        self.checkBox_2.setMinimumSize(QtCore.QSize(0, 27))
        self.checkBox_2.setSizeIncrement(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout_4.addWidget(self.checkBox_2, 5, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(12, 0, 301, 190))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 190))
        self.groupBox.setMaximumSize(QtCore.QSize(800, 190))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ExperimentTabWidget = QtGui.QTabWidget(self.groupBox)
        self.ExperimentTabWidget.setGeometry(QtCore.QRect(0, 30, 301, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExperimentTabWidget.sizePolicy().hasHeightForWidth())
        self.ExperimentTabWidget.setSizePolicy(sizePolicy)
        self.ExperimentTabWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.ExperimentTabWidget.setMaximumSize(QtCore.QSize(16777215, 150))
        self.ExperimentTabWidget.setObjectName(_fromUtf8("ExperimentTabWidget"))
        self.Files = QtGui.QWidget()
        self.Files.setObjectName(_fromUtf8("Files"))
        self.label = QtGui.QLabel(self.Files)
        self.label.setGeometry(QtCore.QRect(12, 15, 77, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.RootSSX = QtGui.QLineEdit(self.Files)
        self.RootSSX.setGeometry(QtCore.QRect(100, 15, 186, 21))
        self.RootSSX.setObjectName(_fromUtf8("RootSSX"))
        self.label_2 = QtGui.QLabel(self.Files)
        self.label_2.setGeometry(QtCore.QRect(12, 45, 78, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.FileExtensionSSX = QtGui.QLineEdit(self.Files)
        self.FileExtensionSSX.setGeometry(QtCore.QRect(100, 45, 186, 21))
        self.FileExtensionSSX.setObjectName(_fromUtf8("FileExtensionSSX"))
        self.DataPath = QtGui.QLineEdit(self.Files)
        self.DataPath.setGeometry(QtCore.QRect(100, 75, 186, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DataPath.setFont(font)
        self.DataPath.setObjectName(_fromUtf8("DataPath"))
        self.DataPathBut = QtGui.QToolButton(self.Files)
        self.DataPathBut.setGeometry(QtCore.QRect(70, 75, 21, 21))
        self.DataPathBut.setText(_fromUtf8(""))
        self.DataPathBut.setObjectName(_fromUtf8("DataPathBut"))
        self.label_7 = QtGui.QLabel(self.Files)
        self.label_7.setGeometry(QtCore.QRect(10, 75, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.ExperimentTabWidget.addTab(self.Files, _fromUtf8(""))
        self.HitList = QtGui.QWidget()
        self.HitList.setObjectName(_fromUtf8("HitList"))
        self.DataPath_2 = QtGui.QLineEdit(self.HitList)
        self.DataPath_2.setGeometry(QtCore.QRect(100, 50, 186, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DataPath_2.setFont(font)
        self.DataPath_2.setText(_fromUtf8(""))
        self.DataPath_2.setObjectName(_fromUtf8("DataPath_2"))
        self.label_12 = QtGui.QLabel(self.HitList)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.DataPathBut_2 = QtGui.QToolButton(self.HitList)
        self.DataPathBut_2.setGeometry(QtCore.QRect(70, 50, 21, 21))
        self.DataPathBut_2.setText(_fromUtf8(""))
        self.DataPathBut_2.setObjectName(_fromUtf8("DataPathBut_2"))
        self.ExperimentTabWidget.addTab(self.HitList, _fromUtf8(""))
        self.findBraggBut = QtGui.QPushButton(Form)
        self.findBraggBut.setEnabled(True)
        self.findBraggBut.setGeometry(QtCore.QRect(160, 820, 120, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findBraggBut.sizePolicy().hasHeightForWidth())
        self.findBraggBut.setSizePolicy(sizePolicy)
        self.findBraggBut.setMinimumSize(QtCore.QSize(120, 32))
        self.findBraggBut.setMaximumSize(QtCore.QSize(120, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.findBraggBut.setFont(font)
        self.findBraggBut.setObjectName(_fromUtf8("findBraggBut"))
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(12, 200, 300, 165))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.ResultsPath = QtGui.QLineEdit(self.groupBox_3)
        self.ResultsPath.setGeometry(QtCore.QRect(103, 30, 186, 21))
        self.ResultsPath.setMinimumSize(QtCore.QSize(151, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ResultsPath.setFont(font)
        self.ResultsPath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ResultsPath.setObjectName(_fromUtf8("ResultsPath"))
        self.ResPathBut = QtGui.QToolButton(self.groupBox_3)
        self.ResPathBut.setGeometry(QtCore.QRect(73, 30, 21, 21))
        self.ResPathBut.setText(_fromUtf8(""))
        self.ResPathBut.setObjectName(_fromUtf8("ResPathBut"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(13, 30, 51, 23))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(15, 70, 35, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.hdf5out = QtGui.QCheckBox(self.groupBox_3)
        self.hdf5out.setGeometry(QtCore.QRect(15, 100, 125, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hdf5out.setFont(font)
        self.hdf5out.setChecked(False)
        self.hdf5out.setObjectName(_fromUtf8("hdf5out"))
        self.cctbxout = QtGui.QCheckBox(self.groupBox_3)
        self.cctbxout.setGeometry(QtCore.QRect(15, 130, 149, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cctbxout.setFont(font)
        self.cctbxout.setObjectName(_fromUtf8("cctbxout"))
        self.cbfout = QtGui.QCheckBox(self.groupBox_3)
        self.cbfout.setGeometry(QtCore.QRect(170, 100, 112, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cbfout.setFont(font)
        self.cbfout.setObjectName(_fromUtf8("cbfout"))
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(12, 370, 300, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_23 = QtGui.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(21, 104, 127, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.BKG_SUB = QtGui.QComboBox(self.groupBox_4)
        self.BKG_SUB.setGeometry(QtCore.QRect(161, 104, 100, 26))
        self.BKG_SUB.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.BKG_SUB.setFont(font)
        self.BKG_SUB.setObjectName(_fromUtf8("BKG_SUB"))
        self.BKG_SUB.addItem(_fromUtf8(""))
        self.BKG_SUB.addItem(_fromUtf8(""))
        self.ROI_X1 = QtGui.QLineEdit(self.groupBox_4)
        self.ROI_X1.setGeometry(QtCore.QRect(120, 147, 41, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_X1.sizePolicy().hasHeightForWidth())
        self.ROI_X1.setSizePolicy(sizePolicy)
        self.ROI_X1.setMinimumSize(QtCore.QSize(41, 21))
        self.ROI_X1.setMaximumSize(QtCore.QSize(41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ROI_X1.setFont(font)
        self.ROI_X1.setObjectName(_fromUtf8("ROI_X1"))
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(171, 180, 20, 21))
        self.label_22.setMinimumSize(QtCore.QSize(20, 0))
        self.label_22.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox.setGeometry(QtCore.QRect(20, 147, 44, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(92, 180, 20, 21))
        self.label_21.setMinimumSize(QtCore.QSize(20, 21))
        self.label_21.setMaximumSize(QtCore.QSize(20, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.ROI_Y1 = QtGui.QLineEdit(self.groupBox_4)
        self.ROI_Y1.setGeometry(QtCore.QRect(199, 147, 41, 21))
        self.ROI_Y1.setMinimumSize(QtCore.QSize(41, 0))
        self.ROI_Y1.setMaximumSize(QtCore.QSize(41, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ROI_Y1.setFont(font)
        self.ROI_Y1.setObjectName(_fromUtf8("ROI_Y1"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(171, 147, 20, 21))
        self.label_20.setMinimumSize(QtCore.QSize(20, 0))
        self.label_20.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.ROI_Y2 = QtGui.QLineEdit(self.groupBox_4)
        self.ROI_Y2.setGeometry(QtCore.QRect(199, 180, 41, 21))
        self.ROI_Y2.setMinimumSize(QtCore.QSize(41, 0))
        self.ROI_Y2.setMaximumSize(QtCore.QSize(41, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ROI_Y2.setFont(font)
        self.ROI_Y2.setObjectName(_fromUtf8("ROI_Y2"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(92, 147, 20, 21))
        self.label_19.setMinimumSize(QtCore.QSize(20, 21))
        self.label_19.setMaximumSize(QtCore.QSize(20, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.ROI_X2 = QtGui.QLineEdit(self.groupBox_4)
        self.ROI_X2.setGeometry(QtCore.QRect(120, 180, 41, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROI_X2.sizePolicy().hasHeightForWidth())
        self.ROI_X2.setSizePolicy(sizePolicy)
        self.ROI_X2.setMinimumSize(QtCore.QSize(41, 21))
        self.ROI_X2.setMaximumSize(QtCore.QSize(41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ROI_X2.setFont(font)
        self.ROI_X2.setObjectName(_fromUtf8("ROI_X2"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(21, 33, 78, 21))
        self.label_10.setMinimumSize(QtCore.QSize(78, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.DarkDelBut = QtGui.QToolButton(self.groupBox_4)
        self.DarkDelBut.setGeometry(QtCore.QRect(263, 32, 21, 21))
        self.DarkDelBut.setText(_fromUtf8(""))
        self.DarkDelBut.setObjectName(_fromUtf8("DarkDelBut"))
        self.DarkPath = QtGui.QLineEdit(self.groupBox_4)
        self.DarkPath.setGeometry(QtCore.QRect(103, 33, 151, 21))
        self.DarkPath.setMinimumSize(QtCore.QSize(151, 0))
        self.DarkPath.setMaximumSize(QtCore.QSize(151, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DarkPath.setFont(font)
        self.DarkPath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DarkPath.setObjectName(_fromUtf8("DarkPath"))
        self.MaskPath = QtGui.QLineEdit(self.groupBox_4)
        self.MaskPath.setGeometry(QtCore.QRect(103, 70, 151, 21))
        self.MaskPath.setMinimumSize(QtCore.QSize(151, 0))
        self.MaskPath.setMaximumSize(QtCore.QSize(151, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.MaskPath.setFont(font)
        self.MaskPath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.MaskPath.setObjectName(_fromUtf8("MaskPath"))
        self.MaskDelBut = QtGui.QToolButton(self.groupBox_4)
        self.MaskDelBut.setGeometry(QtCore.QRect(263, 69, 21, 21))
        self.MaskDelBut.setText(_fromUtf8(""))
        self.MaskDelBut.setObjectName(_fromUtf8("MaskDelBut"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(21, 70, 78, 21))
        self.label_11.setMinimumSize(QtCore.QSize(78, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.DarkPathBut = QtGui.QToolButton(self.groupBox_4)
        self.DarkPathBut.setGeometry(QtCore.QRect(73, 33, 21, 21))
        self.DarkPathBut.setText(_fromUtf8(""))
        self.DarkPathBut.setObjectName(_fromUtf8("DarkPathBut"))
        self.MaskPathBut = QtGui.QToolButton(self.groupBox_4)
        self.MaskPathBut.setGeometry(QtCore.QRect(73, 70, 21, 21))
        self.MaskPathBut.setText(_fromUtf8(""))
        self.MaskPathBut.setObjectName(_fromUtf8("MaskPathBut"))
        self.PlayButton_2 = QtGui.QPushButton(Form)
        self.PlayButton_2.setEnabled(True)
        self.PlayButton_2.setGeometry(QtCore.QRect(20, 820, 120, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlayButton_2.sizePolicy().hasHeightForWidth())
        self.PlayButton_2.setSizePolicy(sizePolicy)
        self.PlayButton_2.setMinimumSize(QtCore.QSize(120, 32))
        self.PlayButton_2.setMaximumSize(QtCore.QSize(120, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PlayButton_2.setFont(font)
        self.PlayButton_2.setObjectName(_fromUtf8("PlayButton_2"))

        self.retranslateUi(Form)
        self.ExperimentTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Hit Finding", None))
        self.groupBox_2.setTitle(_translate("Form", "HitFinder Parameters", None))
        self.label_3.setText(_translate("Form", "Threshold", None))
        self.Threshold.setText(_translate("Form", "100", None))
        self.label_4.setText(_translate("Form", "Min Number of pixels", None))
        self.Npixels.setText(_translate("Form", "10", None))
        self.label_5.setText(_translate("Form", "Find Bragg Peaks", None))
        #self.FindBragg.setCurrentText(_translate("Form", "True", None))
        self.FindBragg.setItemText(0, _translate("Form", "True", None))
        self.FindBragg.setItemText(1, _translate("Form", "False", None))
        self.label_6.setText(_translate("Form", "Bragg threshold", None))
        self.BraggThreshold.setText(_translate("Form", "10", None))
        self.label_8.setText(_translate("Form", "# Cpus", None))
        self.cpus.setText(_translate("Form", "4", None))
        self.checkBox_2.setText(_translate("Form", "live", None))
        self.groupBox.setTitle(_translate("Form", "Input", None))
        self.label.setText(_translate("Form", "Filename root", None))
        self.RootSSX.setText(_translate("Form", "b3rod", None))
        self.label_2.setText(_translate("Form", "File extension", None))
        self.FileExtensionSSX.setText(_translate("Form", ".cbf", None))
        self.DataPath.setText(_translate("Form", "/Users/coquelleni/PycharmProjects/tmp/tmp/", None))
        self.label_7.setText(_translate("Form", "Data path", None))
        self.ExperimentTabWidget.setTabText(self.ExperimentTabWidget.indexOf(self.Files), _translate("Form", "Files", None))
        self.label_12.setText(_translate("Form", "Hit File", None))
        self.ExperimentTabWidget.setTabText(self.ExperimentTabWidget.indexOf(self.HitList), _translate("Form", "Hit List", None))
        self.findBraggBut.setText(_translate("Form", "Find Bragg", None))
        self.groupBox_3.setTitle(_translate("Form", "Output", None))
        self.ResultsPath.setText(_translate("Form", "/Users/coquelleni/", None))
        self.label_9.setText(_translate("Form", "Results", None))
        self.label_18.setText(_translate("Form", "Save :", None))
        self.hdf5out.setText(_translate("Form", "h5 crystFEL format", None))
        self.cctbxout.setText(_translate("Form", "cctbx.xfel pickle format", None))
        self.cbfout.setText(_translate("Form", "nXDS cbf format", None))
        self.groupBox_4.setTitle(_translate("Form", "Corrections and ROI", None))
        self.label_23.setText(_translate("Form", "Background Subtraction", None))
        self.BKG_SUB.setItemText(0, _translate("Form", "None", None))
        self.BKG_SUB.setItemText(1, _translate("Form", "Azimut Int", None))
        self.ROI_X1.setText(_translate("Form", "20", None))
        self.label_22.setText(_translate("Form", "Y2", None))
        self.checkBox.setText(_translate("Form", "ROI", None))
        self.label_21.setText(_translate("Form", "X2", None))
        self.ROI_Y1.setText(_translate("Form", "900", None))
        self.label_20.setText(_translate("Form", "Y1", None))
        self.ROI_Y2.setText(_translate("Form", "900", None))
        self.label_19.setText(_translate("Form", "X1", None))
        self.ROI_X2.setText(_translate("Form", "20", None))
        self.label_10.setText(_translate("Form", "Dark", None))
        self.DarkPath.setText(_translate("Form", "/Users/coquelleni/", None))
        self.MaskPath.setText(_translate("Form", "/Users/coquelleni/", None))
        self.label_11.setText(_translate("Form", "Mask", None))
        self.PlayButton_2.setText(_translate("Form", "Find Hits", None))

