# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'npc_qt.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_NPC(object):
    def setupUi(self, NPC):
        NPC.setObjectName(_fromUtf8("NPC"))
        NPC.resize(1576, 1001)
        #NPC.setFrameShape(QtGui.QFrame.StyledPanel)
        #NPC.setFrameShadow(QtGui.QFrame.Raised)
        self.menubar = QtGui.QMenuBar(NPC)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuBragg_Peaks_Form = QtGui.QMenu(self.menuOptions)
        self.menuBragg_Peaks_Form.setObjectName(_fromUtf8("menuBragg_Peaks_Form"))
        self.ExperimentTabWidget = QtGui.QTabWidget(NPC)
        self.ExperimentTabWidget.setGeometry(QtCore.QRect(20, 20, 286, 115))
        self.ExperimentTabWidget.setObjectName(_fromUtf8("ExperimentTabWidget"))
        self.SSX = QtGui.QWidget()
        self.SSX.setObjectName(_fromUtf8("SSX"))
        self.gridLayout = QtGui.QGridLayout(self.SSX)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.SSX)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.RootSSX = QtGui.QLineEdit(self.SSX)
        self.RootSSX.setObjectName(_fromUtf8("RootSSX"))
        self.gridLayout.addWidget(self.RootSSX, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.SSX)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.FileExtensionSSX = QtGui.QLineEdit(self.SSX)
        self.FileExtensionSSX.setObjectName(_fromUtf8("FileExtensionSSX"))
        self.gridLayout.addWidget(self.FileExtensionSSX, 1, 1, 1, 1)
        self.ExperimentTabWidget.addTab(self.SSX, _fromUtf8(""))
        self.SACLA = QtGui.QWidget()
        self.SACLA.setObjectName(_fromUtf8("SACLA"))
        self.label_23 = QtGui.QLabel(self.SACLA)
        self.label_23.setGeometry(QtCore.QRect(20, 30, 88, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.RunNumberSFX = QtGui.QLineEdit(self.SACLA)
        self.RunNumberSFX.setGeometry(QtCore.QRect(116, 30, 144, 21))
        self.RunNumberSFX.setObjectName(_fromUtf8("RunNumberSFX"))
        self.ExperimentTabWidget.addTab(self.SACLA, _fromUtf8(""))
        self.LCLS = QtGui.QWidget()
        self.LCLS.setObjectName(_fromUtf8("LCLS"))
        self.ExperimentLCLS = QtGui.QLineEdit(self.LCLS)
        self.ExperimentLCLS.setGeometry(QtCore.QRect(116, 9, 144, 21))
        self.ExperimentLCLS.setObjectName(_fromUtf8("ExperimentLCLS"))
        self.label_21 = QtGui.QLabel(self.LCLS)
        self.label_21.setGeometry(QtCore.QRect(20, 9, 88, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.LCLS)
        self.label_22.setGeometry(QtCore.QRect(20, 40, 88, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.RunnumberLCLS = QtGui.QLineEdit(self.LCLS)
        self.RunnumberLCLS.setGeometry(QtCore.QRect(116, 40, 144, 21))
        self.RunnumberLCLS.setObjectName(_fromUtf8("RunnumberLCLS"))
        self.ExperimentTabWidget.addTab(self.LCLS, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(NPC)
        self.groupBox.setGeometry(QtCore.QRect(20, 140, 286, 341))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(10, 210, 261, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 230, 184, 102))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout.addWidget(self.label_18)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.hdf5out = QtGui.QCheckBox(self.layoutWidget)
        self.hdf5out.setObjectName(_fromUtf8("hdf5out"))
        self.verticalLayout.addWidget(self.hdf5out)
        self.cctbxout = QtGui.QCheckBox(self.layoutWidget)
        self.cctbxout.setObjectName(_fromUtf8("cctbxout"))
        self.verticalLayout.addWidget(self.cctbxout)
        self.cbfout = QtGui.QCheckBox(self.layoutWidget)
        self.cbfout.setObjectName(_fromUtf8("cbfout"))
        self.verticalLayout.addWidget(self.cbfout)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 247, 166))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.DataPathBut = QtGui.QPushButton(self.layoutWidget1)
        self.DataPathBut.setObjectName(_fromUtf8("DataPathBut"))
        self.gridLayout_2.addWidget(self.DataPathBut, 0, 0, 1, 1)
        self.DataPath = QtGui.QLineEdit(self.layoutWidget1)
        self.DataPath.setObjectName(_fromUtf8("DataPath"))
        self.gridLayout_2.addWidget(self.DataPath, 0, 1, 1, 1)
        self.ResPathBut = QtGui.QPushButton(self.layoutWidget1)
        self.ResPathBut.setObjectName(_fromUtf8("ResPathBut"))
        self.gridLayout_2.addWidget(self.ResPathBut, 1, 0, 1, 1)
        self.ResultsPath = QtGui.QLineEdit(self.layoutWidget1)
        self.ResultsPath.setText(_fromUtf8(""))
        self.ResultsPath.setObjectName(_fromUtf8("ResultsPath"))
        self.gridLayout_2.addWidget(self.ResultsPath, 1, 1, 1, 1)
        self.DarkPathBut = QtGui.QPushButton(self.layoutWidget1)
        self.DarkPathBut.setObjectName(_fromUtf8("DarkPathBut"))
        self.gridLayout_2.addWidget(self.DarkPathBut, 2, 0, 1, 1)
        self.DarkPath = QtGui.QLineEdit(self.layoutWidget1)
        self.DarkPath.setObjectName(_fromUtf8("DarkPath"))
        self.gridLayout_2.addWidget(self.DarkPath, 2, 1, 1, 1)
        self.MaskPathBut = QtGui.QPushButton(self.layoutWidget1)
        self.MaskPathBut.setObjectName(_fromUtf8("MaskPathBut"))
        self.gridLayout_2.addWidget(self.MaskPathBut, 3, 0, 1, 1)
        self.MaskPath = QtGui.QLineEdit(self.layoutWidget1)
        self.MaskPath.setObjectName(_fromUtf8("MaskPath"))
        self.gridLayout_2.addWidget(self.MaskPath, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.cpus = QtGui.QLineEdit(self.layoutWidget1)
        self.cpus.setObjectName(_fromUtf8("cpus"))
        self.gridLayout_2.addWidget(self.cpus, 4, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(NPC)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 490, 286, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 30, 261, 115))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.Threshold = QtGui.QLineEdit(self.layoutWidget2)
        self.Threshold.setObjectName(_fromUtf8("Threshold"))
        self.gridLayout_3.addWidget(self.Threshold, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.Npixels = QtGui.QLineEdit(self.layoutWidget2)
        self.Npixels.setObjectName(_fromUtf8("Npixels"))
        self.gridLayout_3.addWidget(self.Npixels, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.FindBragg = QtGui.QComboBox(self.layoutWidget2)
        self.FindBragg.setObjectName(_fromUtf8("FindBragg"))
        self.FindBragg.addItem(_fromUtf8(""))
        self.FindBragg.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.FindBragg, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.BraggThreshold = QtGui.QLineEdit(self.layoutWidget2)
        self.BraggThreshold.setObjectName(_fromUtf8("BraggThreshold"))
        self.gridLayout_3.addWidget(self.BraggThreshold, 3, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(NPC)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 660, 286, 161))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(12, 30, 269, 118))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_13 = QtGui.QLabel(self.layoutWidget3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 0, 0, 1, 1)
        self.Detector = QtGui.QComboBox(self.layoutWidget3)
        self.Detector.setObjectName(_fromUtf8("Detector"))
        self.Detector.addItem(_fromUtf8(""))
        self.Detector.addItem(_fromUtf8(""))
        self.Detector.addItem(_fromUtf8(""))
        self.Detector.addItem(_fromUtf8(""))
        self.Detector.addItem(_fromUtf8(""))
        self.Detector.addItem(_fromUtf8(""))
        self.Detector.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.Detector, 0, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget3)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 1, 0, 1, 1)
        self.Wavelength = QtGui.QLineEdit(self.layoutWidget3)
        self.Wavelength.setObjectName(_fromUtf8("Wavelength"))
        self.gridLayout_6.addWidget(self.Wavelength, 1, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 2, 0, 1, 1)
        self.distance = QtGui.QLineEdit(self.layoutWidget3)
        self.distance.setObjectName(_fromUtf8("distance"))
        self.gridLayout_6.addWidget(self.distance, 2, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_16 = QtGui.QLabel(self.layoutWidget3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout.addWidget(self.label_16)
        self.beamX = QtGui.QLineEdit(self.layoutWidget3)
        self.beamX.setObjectName(_fromUtf8("beamX"))
        self.horizontalLayout.addWidget(self.beamX)
        self.label_17 = QtGui.QLabel(self.layoutWidget3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout.addWidget(self.label_17)
        self.beamY = QtGui.QLineEdit(self.layoutWidget3)
        self.beamY.setText(_fromUtf8(""))
        self.beamY.setObjectName(_fromUtf8("beamY"))
        self.horizontalLayout.addWidget(self.beamY)
        self.gridLayout_6.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        self.graphicsView = GraphicsLayoutWidget(NPC)
        self.graphicsView.setGeometry(QtCore.QRect(320, 30, 891, 871))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.groupBox_4 = QtGui.QGroupBox(NPC)
        self.groupBox_4.setGeometry(QtCore.QRect(1220, 20, 351, 201))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 40, 213, 141))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Boost = QtGui.QLineEdit(self.layoutWidget4)
        self.Boost.setObjectName(_fromUtf8("Boost"))
        self.gridLayout_4.addWidget(self.Boost, 0, 1, 1, 1)
        self.ColorMap = QtGui.QComboBox(self.layoutWidget4)
        self.ColorMap.setObjectName(_fromUtf8("ColorMap"))
        self.ColorMap.addItem(_fromUtf8(""))
        self.ColorMap.addItem(_fromUtf8(""))
        self.ColorMap.addItem(_fromUtf8(""))
        self.ColorMap.addItem(_fromUtf8(""))
        self.ColorMap.addItem(_fromUtf8(""))
        self.ColorMap.addItem(_fromUtf8(""))
        self.ColorMap.addItem(_fromUtf8(""))
        self.ColorMap.addItem(_fromUtf8(""))
        self.ColorMap.addItem(_fromUtf8(""))
        self.ColorMap.addItem(_fromUtf8(""))
        self.ColorMap.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.ColorMap, 3, 1, 1, 1)
        self.Min = QtGui.QLineEdit(self.layoutWidget4)
        self.Min.setObjectName(_fromUtf8("Min"))
        self.gridLayout_4.addWidget(self.Min, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget4)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget4)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget4)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 3, 0, 1, 1)
        self.Max = QtGui.QLineEdit(self.layoutWidget4)
        self.Max.setObjectName(_fromUtf8("Max"))
        self.gridLayout_4.addWidget(self.Max, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget4)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(NPC)
        self.groupBox_5.setGeometry(QtCore.QRect(1220, 230, 351, 671))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.LoadResultsBut = QtGui.QPushButton(self.groupBox_5)
        self.LoadResultsBut.setGeometry(QtCore.QRect(30, 620, 151, 34))
        self.LoadResultsBut.setObjectName(_fromUtf8("LoadResultsBut"))
        self.PlayButton = QtGui.QPushButton(self.groupBox_5)
        self.PlayButton.setGeometry(QtCore.QRect(180, 620, 71, 32))
        self.PlayButton.setObjectName(_fromUtf8("PlayButton"))
        self.StopButton = QtGui.QPushButton(self.groupBox_5)
        self.StopButton.setGeometry(QtCore.QRect(250, 620, 71, 32))
        self.StopButton.setObjectName(_fromUtf8("StopButton"))
        self.treeWidget = QtGui.QTreeWidget(self.groupBox_5)
        self.treeWidget.setGeometry(QtCore.QRect(10, 30, 331, 581))
        self.treeWidget.setAcceptDrops(True)
        self.treeWidget.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.treeWidget.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.treeWidget.setIndentation(20)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        self.layoutWidget5 = QtGui.QWidget(NPC)
        self.layoutWidget5.setGeometry(QtCore.QRect(40, 870, 241, 32))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.PlayButton_2 = QtGui.QPushButton(self.layoutWidget5)
        self.PlayButton_2.setObjectName(_fromUtf8("PlayButton_2"))
        self.horizontalLayout_2.addWidget(self.PlayButton_2)
        self.FindBraggsButton = QtGui.QPushButton(self.layoutWidget5)
        self.FindBraggsButton.setObjectName(_fromUtf8("FindBraggsButton"))
        self.horizontalLayout_2.addWidget(self.FindBraggsButton)
        self.Log = QtGui.QPlainTextEdit(NPC)
        self.Log.setGeometry(QtCore.QRect(10, 910, 1541, 221))
        self.Log.setObjectName(_fromUtf8("Log"))
        self.actionLoad_Images = QtGui.QAction(NPC)
        self.actionLoad_Images.setObjectName(_fromUtf8("actionLoad_Images"))
        self.actionLoad_geometry = QtGui.QAction(NPC)
        self.actionLoad_geometry.setObjectName(_fromUtf8("actionLoad_geometry"))
        self.actionClose = QtGui.QAction(NPC)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionRings = QtGui.QAction(NPC)
        self.actionRings.setObjectName(_fromUtf8("actionRings"))
        self.actionBragg_Peaks_Size = QtGui.QAction(NPC)
        self.actionBragg_Peaks_Size.setObjectName(_fromUtf8("actionBragg_Peaks_Size"))
        self.actionBragg_Peaks_Color = QtGui.QAction(NPC)
        self.actionBragg_Peaks_Color.setObjectName(_fromUtf8("actionBragg_Peaks_Color"))
        self.actionOverride_Bragg_search_safeguards = QtGui.QAction(NPC)
        self.actionOverride_Bragg_search_safeguards.setObjectName(_fromUtf8("actionOverride_Bragg_search_safeguards"))
        self.actionShow_Beam_Center = QtGui.QAction(NPC)
        self.actionShow_Beam_Center.setObjectName(_fromUtf8("actionShow_Beam_Center"))
        self.actionShow_resolution_rings = QtGui.QAction(NPC)
        self.actionShow_resolution_rings.setObjectName(_fromUtf8("actionShow_resolution_rings"))
        self.actionSquares = QtGui.QAction(NPC)
        self.actionSquares.setObjectName(_fromUtf8("actionSquares"))
        self.actionShow_Bragg_Peaks = QtGui.QAction(NPC)
        self.actionShow_Bragg_Peaks.setObjectName(_fromUtf8("actionShow_Bragg_Peaks"))
        self.menuFile.addAction(self.actionLoad_Images)
        self.menuFile.addAction(self.actionLoad_geometry)
        self.menuFile.addAction(self.actionClose)
        self.menuBragg_Peaks_Form.addAction(self.actionRings)
        self.menuBragg_Peaks_Form.addAction(self.actionSquares)
        self.menuOptions.addAction(self.actionShow_Beam_Center)
        self.menuOptions.addAction(self.actionShow_resolution_rings)
        self.menuOptions.addAction(self.actionShow_Bragg_Peaks)
        self.menuOptions.addAction(self.actionBragg_Peaks_Size)
        self.menuOptions.addAction(self.menuBragg_Peaks_Form.menuAction())
        self.menuOptions.addAction(self.actionBragg_Peaks_Color)
        self.menuOptions.addAction(self.actionOverride_Bragg_search_safeguards)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(NPC)
        self.ExperimentTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NPC)

    def retranslateUi(self, NPC):
        NPC.setWindowTitle(_translate("NPC", "Frame", None))
        self.menuFile.setTitle(_translate("NPC", "File", None))
        self.menuEdit.setTitle(_translate("NPC", "Edit", None))
        self.menuOptions.setTitle(_translate("NPC", "Options", None))
        self.menuBragg_Peaks_Form.setTitle(_translate("NPC", "Bragg Peaks Form", None))
        self.label.setText(_translate("NPC", "Filename root", None))
        self.label_2.setText(_translate("NPC", "File extension", None))
        self.ExperimentTabWidget.setTabText(self.ExperimentTabWidget.indexOf(self.SSX), _translate("NPC", "SSX", None))
        self.label_23.setText(_translate("NPC", "Run number", None))
        self.ExperimentTabWidget.setTabText(self.ExperimentTabWidget.indexOf(self.SACLA), _translate("NPC", "SFX_SACLA", None))
        self.label_21.setText(_translate("NPC", "Experiment", None))
        self.label_22.setText(_translate("NPC", "Run number", None))
        self.ExperimentTabWidget.setTabText(self.ExperimentTabWidget.indexOf(self.LCLS), _translate("NPC", "SFX_LCLS", None))
        self.groupBox.setTitle(_translate("NPC", "General Parameters", None))
        self.label_18.setText(_translate("NPC", "Output Formats", None))
        self.hdf5out.setText(_translate("NPC", "h5 crystFEL format", None))
        self.cctbxout.setText(_translate("NPC", "cctbx.xfel pickle format", None))
        self.cbfout.setText(_translate("NPC", "nXDS cbf format", None))
        self.DataPathBut.setText(_translate("NPC", "Data", None))
        self.ResPathBut.setText(_translate("NPC", "Results", None))
        self.DarkPathBut.setText(_translate("NPC", "Dark", None))
        self.MaskPathBut.setText(_translate("NPC", "Mask", None))
        self.label_8.setText(_translate("NPC", "# Cpus", None))
        self.groupBox_2.setTitle(_translate("NPC", "HitFinder Parameters", None))
        self.label_3.setText(_translate("NPC", "Threshold", None))
        self.label_4.setText(_translate("NPC", "Min Number of pixels", None))
        self.label_5.setText(_translate("NPC", "Find Bragg Peaks", None))
        self.FindBragg.setItemText(0, _translate("NPC", "True", None))
        self.FindBragg.setItemText(1, _translate("NPC", "False", None))
        self.label_6.setText(_translate("NPC", "Bragg Threshold", None))
        self.groupBox_3.setTitle(_translate("NPC", "Experimental Parameters", None))
        self.label_13.setText(_translate("NPC", "Detector", None))
        self.Detector.setItemText(0, _translate("NPC", "Pilatus1M", None))
        self.Detector.setItemText(1, _translate("NPC", "Pilatus2M", None))
        self.Detector.setItemText(2, _translate("NPC", "Pilatus6M", None))
        self.Detector.setItemText(3, _translate("NPC", "EIger1M", None))
        self.Detector.setItemText(4, _translate("NPC", "Eiger4M", None))
        self.Detector.setItemText(5, _translate("NPC", "MPCCD", None))
        self.Detector.setItemText(6, _translate("NPC", "CSPAD", None))
        self.label_14.setText(_translate("NPC", "Wavelength (A)", None))
        self.label_15.setText(_translate("NPC", "Detector distance (mm)", None))
        self.label_16.setText(_translate("NPC", "Beam Center X", None))
        self.label_17.setText(_translate("NPC", "Y", None))
        self.groupBox_4.setTitle(_translate("NPC", "Viewer Settings", None))
        self.Boost.setText(_translate("NPC", "1", None))
        self.ColorMap.setItemText(0, _translate("NPC", "Hot", None))
        self.ColorMap.setItemText(1, _translate("NPC", "Gray", None))
        self.ColorMap.setItemText(2, _translate("NPC", "Gray_r", None))
        self.ColorMap.setItemText(3, _translate("NPC", "YGB_r", None))
        self.ColorMap.setItemText(4, _translate("NPC", "Blues", None))
        self.ColorMap.setItemText(5, _translate("NPC", "Blues_r", None))
        self.ColorMap.setItemText(6, _translate("NPC", "Reds", None))
        self.ColorMap.setItemText(7, _translate("NPC", "Reds_r", None))
        self.ColorMap.setItemText(8, _translate("NPC", "Jet", None))
        self.ColorMap.setItemText(9, _translate("NPC", "Spectral", None))
        self.ColorMap.setItemText(10, _translate("NPC", "Spectral_r", None))
        self.Min.setText(_translate("NPC", "0", None))
        self.label_9.setText(_translate("NPC", "Max Value", None))
        self.label_11.setText(_translate("NPC", "Min Value", None))
        self.label_12.setText(_translate("NPC", "Color maps", None))
        self.Max.setText(_translate("NPC", "10", None))
        self.label_10.setText(_translate("NPC", "Intensity Boost", None))
        self.groupBox_5.setTitle(_translate("NPC", "Results", None))
        self.LoadResultsBut.setText(_translate("NPC", "Load Images...", None))
        self.PlayButton.setText(_translate("NPC", "Play", None))
        self.StopButton.setText(_translate("NPC", "Stop", None))
        self.treeWidget.headerItem().setText(0, _translate("NPC", "Filename", None))
        self.treeWidget.headerItem().setText(1, _translate("NPC", "# Frames", None))
        self.PlayButton_2.setText(_translate("NPC", "Find Hits", None))
        self.FindBraggsButton.setText(_translate("NPC", "Find Braggs", None))
        self.actionLoad_Images.setText(_translate("NPC", "Load Images", None))
        self.actionLoad_geometry.setText(_translate("NPC", "Load geometry", None))
        self.actionClose.setText(_translate("NPC", "Close", None))
        self.actionRings.setText(_translate("NPC", "Rings", None))
        self.actionBragg_Peaks_Size.setText(_translate("NPC", "Bragg Peaks Size", None))
        self.actionBragg_Peaks_Color.setText(_translate("NPC", "Bragg Peaks Color", None))
        self.actionOverride_Bragg_search_safeguards.setText(_translate("NPC", "Override Bragg search safeguards", None))
        self.actionShow_Beam_Center.setText(_translate("NPC", "Show Beam Center", None))
        self.actionShow_resolution_rings.setText(_translate("NPC", "Show Resolution Rings", None))
        self.actionSquares.setText(_translate("NPC", "Squares", None))
        self.actionShow_Bragg_Peaks.setText(_translate("NPC", "Show Bragg Peaks", None))

from pyqtgraph import GraphicsLayoutWidget
